name: angular-translate Blog
markdown: redcarpet
pygments: true

permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 6

paginate_path: "/page:num"
